### ISSUE TITLE
Some Advices

### ISSUE THREAD

**Issue by jackpgao** [logzio/elasticsearch-benchmark-tool#2]
At first I use es-rally tool to run benchmark on es, actually, it really not working so good .

After I found this project, I like the theory you put here: https://logz.io/blog/benchmarking-elasticsearch-magnetic-ebs/?utm_content=buffer804f1&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Such as it use docker, and I can launch instance as many as I want.

But I have few questions:
1. The metrics in Graphite is not easy to understand, can you provide a table with description.

2. Actually I use Grafana to visualize the status of es, can you provide a Grafana template?

3. The parameter like 'SERVICE_HOST' is not very clearly, I really don't know what it meas.

**Comment by roiravhon** [comment]
Hey @jackpgao and thanks for the feedback!

1. I see. Tried to name the metrics as descriptive as I can. Anyone, in particular, is not clear?
2. I'll see if i can get something out. but for now, its just 5/6 metrics so should be hard to build a dashboard for them
3. Is taken from this https://github.com/logzio/jmx2graphite . Basically, your server name

**Comment by jackpgao** [comment]
Hi, @roiravhon , thanks for you reply.

Actually I have few Questions:

1. the metric 'averageSearchTimeMs', it seems a current value, which means the avg search response time .

2. the metric 'totalSuccessfulSearchsTimeMs', it seems a total value of search time, I should use totalSuccessfulSearchsTimeMs/(numberOfSuccessfuleSearchs+ numberOfFailedSearchs) as the avg query time, is it right?

3. The parameter 'SERVICE_HOST', is it the same with the parameter 'elasticsearchAddress' in  conf file?

**Comment by roiravhon** [comment]
you are right about 1 & 2.
Actually, the average is calualated exactly like that - see here https://github.com/logzio/elasticsearch-benchmark-tool/blob/master/src/main/java/io/logz/benchmarks/elasticsearch/metrics/SearchMbean.java#L52

And 3 - this is totally up to you. This will be the prefix at graphite, for your convenience

**Comment by roiravhon** [comment]
So can this be closed @jackpgao ?
